[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
kzte_oracle = "9FZHqpq5ffv8HLKtWMjVU8WuNTUH44WDYeKr6MEtx7ex"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p integration-tests -- --nocapture"
