[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
kzte_oracle = "3jFfb765du9EE86BRxcscnasbgKZV1s5DdxtAuSJccXo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p integration-tests -- --nocapture"
