[rpc]
http_url = "https://api.devnet.solana.com"
ws_url = "wss://api.devnet.solana.com/"
keypair_path = "~/.config/solana/id.json"
program_id = "3jFfb765du9EE86BRxcscnasbgKZV1s5DdxtAuSJccXo"

[oracle]
config_pubkey = "FGTbFFgrb8L13FsPjktGsTHVb7HNh1VoxkmhTghSYT4M"
publisher_set_pubkey = "C2RAVpyMAcwRF8KnecppxfiR2Xqwrf3FVhYRmw2zUyLk"

[feeds]
kzte_kzt = "Er8w5YUB8mLarQRYma1mTpThEzvcpKP8BYjQEiZpFiLs"
kzte_usd = "GKF4NGMF7gpYHRcN4ywCKPfMGnrzDJQWmr6bMXhixRZp"
kzte_usdc = ""
